---
title: "report_GSI_by_cutoff"
author: "Matthew Bootsma"
date: "August 19, 2019"
output: html_document
---

```{r}
library(dplyr)
```
# POP
```{r}
panel_name = "FST_600"

load(paste("./",panel_name,"/POP_hundy_sim_results",panel_name,".rda", sep = ""))
POP_sim_result = repu_hundy_results$indiv_posteriors
rm(repu_hundy_results)
```

```{r}
test_report = POP_sim_result %>% 
  group_by(collection_scenario, iter, indiv) %>% 
  filter(PofZ == max(PofZ))
```

```{r}
test_report2 = test_report %>% 
  group_by(simulated_collection,collection) %>% 
  summarise(
    prop_assigned = length(which(PofZ>0.7))/200000, 
    n_unassigned = length(which(PofZ<0.7)), 
    nsims = length(PofZ)
  )

whitelistXY = read.csv("./sim_XY_whitelist.csv")


test_report2$simed_from_Ycoord = NA
test_report2$assigned_to_Xcoord = NA

for (i in 1:nrow(whitelistXY)) {
    test_report2[which(test_report2$simulated_collection == whitelistXY[i,"Pop"]),"simed_from_Ycoord"] = whitelistXY[i,"XY_pop"]
    test_report2[which(test_report2$collection == whitelistXY[i,"Pop"]),"assigned_to_Xcoord"] = whitelistXY[i,"XY_pop"]
}


write.csv(test_report2,file = paste("./",panel_name,"/POP_sim_to_plot_",panel_name,".csv", sep = ""), row.names = F)
```

```{r}
test_report2[which(test_report2$prop_assigned < 0.01),"simed_from_Ycoord"] = NA
dat_2_plot = test_report2

ggplot(dat_2_plot, aes(x = assigned_to_Xcoord, y = simed_from_Ycoord, size = prop_assigned))+
  geom_point(shape = 21, fill = "gray", color = "black", 
             alpha = 0.5, inherit.aes = T, 
             size = (18*dat_2_plot$prop_assigned))+
  geom_text(aes(label=round(prop_assigned*100,0)), 
            size = 8)+
  #DID YOU CODE THE XY VALUES CORRECTLY ABOVE? SEE auto_axis_list
  scale_x_continuous(
    breaks = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20),
    labels = c('Delavan', 'Wolf River', 'Lake Wisconsin', 'Medicine Lake', 'Willow Flowage', 'Kawaguesaga', 'Big Arbor Vitae', 'Manitowish Lake', 'Turtle Flambeau', 'Chippewa Flowage', 'Eau Claire River', 'St Louis', 'Pike River', 'Sarah Lake', 'Lake Koronis', 'Mille Lacs', 'Pine River', 'Cutfoot Sioux', 'Ottertail Lake', 'Red Lake')
    )+
  #DID YOU CODE THE XY VALUES CORRECTLY ABOVE? SEE auto_axis_list
  scale_y_continuous(
    breaks = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20),
    labels = c('Delavan', 'Wolf River', 'Lake Wisconsin', 'Medicine Lake', 'Willow Flowage', 'Kawaguesaga', 'Big Arbor Vitae', 'Manitowish Lake', 'Turtle Flambeau', 'Chippewa Flowage', 'Eau Claire River', 'St Louis', 'Pike River', 'Sarah Lake', 'Lake Koronis', 'Mille Lacs', 'Pine River', 'Cutfoot Sioux', 'Ottertail Lake', 'Red Lake')
                       )+
  labs(x = "Assigned Population", y = "Simulated Population")+
  theme(
    plot.title = element_text(hjust = 0.5, size = 28),
    axis.title = element_text(size = 22),
    axis.text.x = element_text(angle = 90, hjust = 1, size = 16),
    axis.text.y = element_text(size = 16),
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "#666666"),
    panel.border = element_rect(colour = "#666666", fill=NA, size=1),
    legend.position = "none"
  )+
  geom_hline(yintercept = c(2.5,7.5,13.5))+
  geom_vline(xintercept = c(2.5,7.5,13.5))+
  ggsave(filename = paste("./",panel_name,"/POP_", panel_name, ".jpg", sep = ""), width = 11.5, height = 11.5, dpi = 350)
```


# REPU
```{r}
load(paste("./",panel_name,"/REPU_hundy_sim_results",panel_name,".rda", sep = ""))
POP_sim_result = repu_hundy_results$indiv_posteriors
rm(repu_hundy_results)
```

```{r}
test_report = POP_sim_result %>% 
  group_by(repunit_scenario, iter, indiv) %>% 
  filter(PofZ == max(PofZ))
```

```{r}
test_report2 = test_report %>% 
  group_by(simulated_repunit,repunit) %>% 
  summarise(
    prop_assigned = length(which(PofZ>0.7))/200000, 
    n_unassigned = length(which(PofZ<0.7)), 
    nsims = length(PofZ)
  )

whitelistXY = read.csv("./sim_XY_whitelist.csv")


test_report2$simed_from_Ycoord = NA
test_report2$assigned_to_Xcoord = NA

for (i in 1:nrow(whitelistXY)) {
    test_report2[which(test_report2$simulated_repunit == whitelistXY[i,"REPU"]),"simed_from_Ycoord"] = whitelistXY[i,"XY_repu"]
    test_report2[which(test_report2$repunit == whitelistXY[i,"REPU"]),"assigned_to_Xcoord"] = whitelistXY[i,"XY_repu"]
}


write.csv(test_report2,file = paste("./",panel_name,"/REPU_sim_to_plot_",panel_name,".csv", sep = ""), row.names = F)
```

```{r}
test_report2[which(test_report2$prop_assigned < 0.01),"simed_from_Ycoord"] = NA
ggplot(test_report2, aes(x = assigned_to_Xcoord, y = simed_from_Ycoord, size = prop_assigned))+
  geom_point(shape = 21, fill = "gray", color = "black", 
             alpha = 0.5, inherit.aes = T, 
             size = (18*test_report2$prop_assigned))+
  geom_text(aes(label=round(prop_assigned*100,0)), 
            size = 8)+
  #DID YOU CODE THE XY VALUES CORRECTLY ABOVE? SEE auto_axis_list
  scale_x_continuous(
    breaks = c(1,2,3,4,5,6,7,8,9,10,11,12,13),
    labels = c('Delavan', 'Wolf River', 'Wisconsin', 'Chippewa', 'St Louis', 'Pike River', 'Sarah Lake', 'Lake Koronis', 'Mille Lacs', 'Pine River', 'Cutfoot Sioux', 'Ottertail Lake', 'Red Lake')
    )+
  #DID YOU CODE THE XY VALUES CORRECTLY ABOVE? SEE auto_axis_list
  scale_y_continuous(    
    breaks = c(1,2,3,4,5,6,7,8,9,10,11,12,13),
    labels = c('Delavan', 'Wolf River', 'Wisconsin', 'Chippewa', 'St Louis', 'Pike River', 'Sarah Lake', 'Lake Koronis', 'Mille Lacs', 'Pine River', 'Cutfoot Sioux', 'Ottertail Lake', 'Red Lake')
                       )+
  labs(x = "Assigned Reporting Unit", y = "Simulated Reporting Unit")+
  theme(
    plot.title = element_text(hjust = 0.5, size = 28),
    axis.title = element_text(size = 22),
    axis.text.x = element_text(angle = 90, hjust = 1, size = 16),
    axis.text.y = element_text(size = 16),
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "#666666"),
    panel.border = element_rect(colour = "#666666", fill=NA, size=1),
    legend.position = "none"
  )+
  geom_hline(yintercept = 4.5)+
  geom_vline(xintercept = 4.5)+
  ggsave(filename = paste("./",panel_name,"/REPU_", panel_name, ".jpg", sep = ""), width = 11.5, height = 11.5, dpi = 350)
```

# Look at accuracy by sim type

  By POP
```{r}
result_summary_POP = read.csv("./mhapHE_600/POP_sim_to_plot_mhapHE_600.csv")
# Self assignment results
result_summary_POP[which(result_summary_POP$simulated_collection == result_summary_POP$collection),]
# prop unassigned by repu
result_summary_POP %>% 
  group_by(simulated_collection) %>% 
  summarise(sum(n_unassigned)/200000)
# average accuracy by repu
mean(result_summary_POP[which(result_summary_POP$simulated_collection == result_summary_POP$collection),"prop_assigned"])

result_summary_REPU = read.csv(file = paste("./",panel_name,"/REPU_sim_to_plot_", panel_name, ".csv", sep = ""))

# prop unassigned by repu
result_summary_REPU %>% 
  group_by(simulated_repunit) %>% 
  summarise(sum(n_unassigned)/200000)
# average accuracy by repu
mean(result_summary_REPU[which(result_summary_REPU$simulated_repunit == result_summary_REPU$repunit),"prop_assigned"])
```
  By REPU
```{r}
# result_summary_REPU = read.csv("./Composite_600/REPU_sim_to_plot_Composite_600.csv")
# result_summary_REPU = read.csv("./FST_600/REPU_sim_to_plot_FST_600.csv")
result_summary_REPU = read.csv("./mhapHE_600/REPU_sim_to_plot_mhapHE_600.csv")
# Self assignment results
result_summary_REPU[which(result_summary_REPU$simulated_repunit == result_summary_REPU$repunit),1:3]
# prop unassigned by repu
# result_summary_REPU %>% 
#   group_by(simulated_repunit) %>% 
#   summarise(sum(n_unassigned)/200000)
# # average accuracy by repu
# mean(result_summary_REPU[which(result_summary_REPU$simulated_repunit == result_summary_REPU$repunit),"prop_assigned"])
# 
# result_summary_REPU = read.csv(file = paste("./",panel_name,"/REPU_sim_to_plot_", panel_name, ".csv", sep = ""))
# 
# # prop unassigned by repu
# result_summary_REPU %>% 
#   group_by(simulated_repunit) %>% 
#   summarise(sum(n_unassigned)/200000)
# # average accuracy by repu
# mean(result_summary_REPU[which(result_summary_REPU$simulated_repunit == result_summary_REPU$repunit),"prop_assigned"])
```

# Looking an n_unassigned by panel
```{r}
panel_ID = "Composite_600"
# unassigned_calc = read.csv("./Composite_600/REPU_sim_to_plot_Composite_600.csv")
unassigned_calc = read.csv(paste("./",panel_ID,"/REPU_sim_to_plot_",panel_ID,".csv", sep = "")) %>% 
  group_by(simulated_repunit) %>% 
  summarise(prop_unassigned = sum(n_unassigned)/sum(nsims))
unassigned_calc$panel = panel_ID
unassigned_calc$Reporting_Unit = gsub("Rep_U-","",unassigned_calc$simulated_repunit)
# ggplot(tmp_calc)+
#   geom_boxplot(aes(y = prop_unassigned))
```


##Box/violin Plots by repu

```{r}
panel_ID = "mhapHE_600"
load(paste("./",panel_ID,"/REPU_hundy_sim_results",panel_ID,".rda", sep = ""))
# result_summary_REPU = read.csv("./Composite_600/REPU_sim_to_plot_Composite_600.csv")
# result_summary_REPU = read.csv("./FST_600/REPU_sim_to_plot_FST_600.csv")

result_2plot_REPU = repu_hundy_results$indiv_posteriors

result_2plot_REPU2 = result_2plot_REPU %>% 
  group_by(repunit_scenario,iter,indiv) %>% 
  filter(PofZ == max(PofZ)) %>% 
  group_by(collection_scenario, iter, simulated_repunit) %>% 
  summarise(accuracy = length(which(simulated_repunit == repunit & PofZ > 0.7))/200, 
            prop_unassigned = length(which(PofZ < 0.7))/200)

# Calculate point accuracy, no variance
# result_2plot_REPU2 = result_2plot_REPU %>% 
#   group_by(repunit_scenario,iter,indiv) %>% 
#   filter(PofZ > 0.7 & PofZ == max(PofZ) & simulated_repunit == repunit) %>% 
#   group_by(repunit_scenario) %>% 
#   summarise(accuracy = length(which(simulated_repunit == repunit))/200000)

result_2plot_REPU2$panel = panel_ID
result_2plot_REPU2$Reporting_Unit = gsub("Rep_U-","",result_2plot_REPU2$simulated_repunit)

#join data frames
# merged_results_2plot_REPU = result_2plot_REPU2
merged_results_2plot_REPU = rbind.data.frame(merged_results_2plot_REPU,result_2plot_REPU2)
unique(merged_results_2plot_REPU$panel)

# means_dat = merged_results_2plot_REPU

# save(merged_results_2plot_REPU, file =  "./merged_sim_results_2plot.rda")
load("./merged_sim_results_2plot.rda")
```

```{r}
unique(merged_results_2plot_REPU$Reporting_Unit)
merged_results_2plot_REPU$Reporting_Unit = factor(merged_results_2plot_REPU$Reporting_Unit, levels = c("Delavan","Wolf_River","Wisconsin","Chippewa","St_Louis","Pike_River","Sarah_Lake","Lake_Koronis","Mille_Lacs","Pine_River","Cutfoot_Sioux","Ottertail_Lake","Red_Lake"))

unique(merged_results_2plot_REPU$panel)
merged_results_2plot_REPU$panel = factor(merged_results_2plot_REPU$panel, levels =c("FST_600","Composite_600","mhapHE_600"))
```


```{r}
library(ggplot2)
dodge = position_dodge(width = 1)
ggplot(merged_results_2plot_REPU, 

       )+
  geom_violin(position = dodge,
              scale = "width", 
              # fill= "white",
              fill= "#CCFFCC",
              alpha = 0.6,
              # draw_quantiles = c(0.25, 0.5, 0.75),
              aes(
                x = Reporting_Unit,
                y = accuracy, 
                color = panel
                )
              )+
  geom_boxplot(position = dodge,width=.05, outlier.colour = NA,
               aes(
                x = Reporting_Unit,
                y = accuracy, 
                # fill= panel,
                color = panel
                )
               )+
  scale_color_manual(values = c("#FF0000","#000000","#9900FF"), name = "Panel ID")+
  geom_violin(position = dodge,
              scale = "width", 
              fill = "grey80",
              linetype = "dotted",
              aes(
                x = Reporting_Unit,
                y = prop_unassigned, 
                # fill= panel,
                color = panel,
                )
              )+
    geom_boxplot(position = dodge,width=.05, outlier.colour = NA,
               aes(
                x = Reporting_Unit,
                y = prop_unassigned, 
                # fill= panel,
                color = panel
                )
               )+
  # scale_color_manual(values = c("#000000","#000000","#9900FF"), name = "Panel ID")+
  
  ylim(0,1)+
  # stat_summary(fun.y="median", geom="point")
  theme(axis.title = element_text(face = "bold", size = 22),
        axis.text.x = element_text(angle = 90, hjust = 1),
        axis.text = element_text(face="bold", size = 18),
        legend.text = element_text(face="bold", size = 18),
        # legend.position = c(0.98,0.25),
        # legend.justification = c(1,-0.2),
        legend.position = "bottom",
        panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  
  geom_vline(xintercept = c(1.5,2.5,3.5,4.5,5.5,6.5,7.5,8.5,9.5,10.5,11.5,12.5), 
             linetype = "twodash", 
             alpha = 0.3
             )+
  labs(x = "Reporting Unit", y = "Proportion\n")

ggsave("./test2merge_results_violin_plot.jpg", width = 18, height = 9, units = "in", dpi = 350)
```

# Look at results by simulation scenario
```{r}
merged_results_2plot_REPU %>% 
  group_by(simulated_repunit) %>% 
  summarize(mean(accuracy), min(accuracy), max(accuracy))
  
merged_results_2plot_REPU %>% 
  group_by(panel) %>% 
  summarize(mean(accuracy), mean(prop_unassigned))
```

```{r}
library(reshape2)
hsd_dat = read.csv("I:/WAE_RAD_Data/novoseq2/SNPs/GTseq/Pwise_FST/Tukey_HSD_wisc_chip.csv", fileEncoding = "UTF-8-BOM")
analysis_of_variance = aov(P_FST ~ P_comp, data = hsd_dat)
summary(analysis_of_variance)

TukeyHSD(analysis_of_variance)
```

